# Main compute configuration.
compute:

  # Add cloud configuration here.
  provider:
    cluster: prod-2

  # Training configuration.
  train:
    gpus: 1 # Number of GPUs
    instance: g4dn.8xlarge # AWS instance type

    # Your environment variables
    environment:
      TEST: TEST

hyper_params:
  params:
    --bar: 1
    --barry: twenty-four
